__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  '../rtdetrv2/include/dataloader.yml',
  '../rtdetrv2/include/optimizer.yml',
  '../rtdetrv2/include/rtdetrv2_r50vd.yml',
]

output_dir: ./output/rtdetrv2_s_ir_fire_person_noaug

num_classes: 2
remap_mscoco_category: False
eval_spatial_size: [640, 640]
sync_bn: False
find_unused_parameters: False
checkpoint_freq: 10
print_freq: 50

PResNet:
  depth: 18
  freeze_at: -1
  freeze_norm: False
  pretrained: False

HybridEncoder:
  in_channels: [128, 256, 512]
  hidden_dim: 256
  expansion: 0.5

RTDETRTransformerv2:
  num_layers: 3

epoches: 120

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.
  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

train_dataloader:
  dataset:
    img_folder: ./dataset/rgbt3m_fire_person/ir/train
    ann_file: ./dataset/rgbt3m_fire_person/annotations/instances_ir_train.json
    transforms:
      ops:
        - {type: Resize, size: [640, 640]}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
      policy: ~
  collate_fn:
    scales: ~
    stop_epoch: ~
  shuffle: True
  total_batch_size: 16
  num_workers: 4

val_dataloader:
  dataset:
    img_folder: ./dataset/rgbt3m_fire_person/ir/val
    ann_file: ./dataset/rgbt3m_fire_person/annotations/instances_ir_val.json
    transforms:
      ops:
        - {type: Resize, size: [640, 640]}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
  shuffle: False
  total_batch_size: 32
  num_workers: 4
